- name: Backup MikroTik RouterOS Device
  hosts: mikrotik_devices
  gather_facts: false

  vars:
    local_backup_directory: "/ansible/backup"
    ansible_user: admin

  tasks:
    - name: Run /export command and capture output
      ansible.builtin.raw: >
        sshpass -p '{{ ansible_password }}'
        ssh -o StrictHostKeyChecking=no {{ ansible_user }}@{{ ansible_host }} /export
      register: export_output
      delegate_to: localhost

    - name: Save export output to a local file
      ansible.builtin.copy:
        dest: "{{ local_backup_directory }}/{{ ansible_host }}_routeros_export.rsc"
        content: "{{ export_output.stdout }}"
      delegate_to: localhost
